### ISSUE TITLE
Find Krzysztof an apartment

### ISSUE THREAD

**Issue by blackjack021** [KrzysztofSiuda/Project-Orgbit#4]
Issue: Krzysztof doesn't have a place to live
Importance: If Krzysztof doesn't have a comfortable bed to sleep on, he gets grumpy and the project suffers
Potential resolution: Check out www.oakwood.com

**Comment by KrzysztofSiuda** [comment]
Got a solution!

http://www.oakwood.com/furnished-apartments/furnished/US/CA/Los-Angeles/prop8851.html?resultsPerPage=20&sort=avl&radius=30&furnished=true&bedrooms=1&petFriendly=false&startDateString=04/25/2015&endDateString=05/08/2015&quantity=1&distanceType=1&altLocationIndex=-1
